backend:
  name: github
  branch: master

media_library:
  name: cloudinary
  config:
    cloud_name: forgingkeys
    api_key: 254869779336122
public_folder: "/uploads"

collections:
  - name: "post"
    label: "Post"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Cover Image", name: "coverimg", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}